---
nombre: Bochas, tejo y sapo (municipio)
categoria: adultos-mayores
ultima-actualizacion: 2018-02-06
direccion: 
  lugar: Gimnasio Ítalo Favale, cancha 4
horario: 
  - {dia: "miércoles", hora: "10:00 a 12:00", nota: "" }
precio: gratis
nota: | 
  mayores de 50 años.
website: []
telefono: []
email: 
permalink: /ushuaia/entidades/bochas-tejo-sapo-municipio/
---
