---
nombre: Tai chi chuan (municipio)
categoria: adultos-mayores
ultima-actualizacion: 2018-02-06
direccion: 
  lugar: Gimnasio Ítalo Favale, cancha 4
horario: 
  - {dia: "martes y jueves", hora: "09:00 a 12:00", nota: "" }
precio: gratis
nota: | 
  mayores de 50 años.
website: []
telefono: []
email: 
permalink: /ushuaia/entidades/tai-chi-chuan-municipio/
---
