---
nombre: Taller de Folclore (municipio)
categoria: adultos-mayores
ultima-actualizacion: 2018-02-06
direccion: 
  lugar: Centro Comunitario Felipe Varela (Tehuelches 1481) 
horario: 
  - {dia: "lunes", hora: "16:00 a 17:30", nota: "" }
precio: gratis
nota: | 
  mayores de 50 años.
website: []
telefono: []
email: 
permalink: /ushuaia/entidades/taller-folclore-municipio/
---
